linters:
  enable:
    - govet
    - errcheck
    - goimports

run:
  timeout: 5m

issues:
  max-same-issues: 5
  max-issues-per-linter: 10
  exclude-use-default: false

linters-settings:
  goimports:
    local-prefixes: github.com/misikch/ya-practicum-arch-sprint3-telemetry