// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DevicesDeviceIDTelemetryGet implements GET /devices/{device_id}/telemetry operation.
//
// Возвращает исторические данные телеметрии для
// устройства за определённый период времени.
//
// GET /devices/{device_id}/telemetry
func (UnimplementedHandler) DevicesDeviceIDTelemetryGet(ctx context.Context, params DevicesDeviceIDTelemetryGetParams) (r DevicesDeviceIDTelemetryGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DevicesDeviceIDTelemetryLatestGet implements GET /devices/{device_id}/telemetry/latest operation.
//
// Возвращает последнее полученное значение телеметрии
// для устройства.
//
// GET /devices/{device_id}/telemetry/latest
func (UnimplementedHandler) DevicesDeviceIDTelemetryLatestGet(ctx context.Context, params DevicesDeviceIDTelemetryLatestGetParams) (r DevicesDeviceIDTelemetryLatestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DevicesDeviceIDTelemetryPost implements POST /devices/{device_id}/telemetry operation.
//
// Позволяет добавить данные телеметрии для устройства.
//
// POST /devices/{device_id}/telemetry
func (UnimplementedHandler) DevicesDeviceIDTelemetryPost(ctx context.Context, req *DevicesDeviceIDTelemetryPostReq, params DevicesDeviceIDTelemetryPostParams) (r DevicesDeviceIDTelemetryPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
