// Code generated by ogen, DO NOT EDIT.
package api

type DevicesDeviceIDTelemetryGetRes interface {
	devicesDeviceIDTelemetryGetRes()
}

type DevicesDeviceIDTelemetryLatestGetRes interface {
	devicesDeviceIDTelemetryLatestGetRes()
}

type DevicesDeviceIDTelemetryPostRes interface {
	devicesDeviceIDTelemetryPostRes()
}
