name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22 # используйте вашу версию Go

      - name: Install dependencies
        run: go mod download

      - name: Install go.uber.mockgen
        run: go install go.uber.org/mock/mockgen@v0.4.0

      - name: Run go generate
        run: go generate ./...

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run tests
        run: go test ./...

      - name: Build service
        run: go build -o ./build/service ./cmd/service/main.go

      - name: Build worker
        run: go build -o ./build/worker ./cmd/worker/main.go
